export DOCKER_IMAGE_BASE

diff --git a/.github/workflows/build-&-publish-docker-image.yml b/.github/workflows/build-&-publish-docker-image.yml
--- a/.github/workflows/build-&-publish-docker-image.yml
+++ b/.github/workflows/build-&-publish-docker-image.yml
@@ -30,11 +30,11 @@ jobs:
     timeout-minutes: 30
     runs-on: [arc-runner]
     steps:
-      - name: Cleanup before restarting conductor tests.
-        run: |
-          echo 'y' | docker system prune -a || true
-          cd /tmp
-          sudo rm -rf ./*
+      # - name: Cleanup before restarting conductor tests.
+      #   run: |
+      #     echo 'y' | docker system prune -a || true
+      #     cd /tmp
+      #     sudo rm -rf ./*
 
       - name: Set docker image tag
         run: |
@@ -48,10 +48,10 @@ jobs:
           echo "BRANCH=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo ${GITHUB_REF#refs/*/} || echo $GITHUB_HEAD_REF)" >> $GITHUB_ENV
           echo "SHA=$([ -z '${{ github.event.pull_request.head.sha }}' ] && echo $GITHUB_SHA || echo '${{ github.event.pull_request.head.sha }}')" >> $GITHUB_ENV
 
-      - name: Setup go
-        uses: actions/setup-go@v4
-        with:
-          go-version: ^1.21 # The Go version to download (if necessary) and use.
+      # - name: Setup go
+      #   uses: actions/setup-go@v4
+      #   with:
+      #     go-version: ^1.21 # The Go version to download (if necessary) and use.
 
       - name: Clone blobber
         uses: actions/checkout@v3
@@ -90,7 +90,7 @@ jobs:
 
       - name: Build blobber
         run: |
-          # export DOCKER_IMAGE_BASE="$BLOBBER_BUILD_BASE_REGISTRY:$TAG"
+          export DOCKER_IMAGE_BASE="$BLOBBER_BUILD_BASE_REGISTRY:$TAG"
           # export DOCKER_IMAGE_SWAGGER="${BLOBBER_REGISTRY}:swagger_test"
           # # export DOCKER_BUILD="buildx build --platform linux/amd64,linux/arm64 --push"
           # export DOCKER_BUILD="build --push"
